name: Build Static msmtp Binary

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Build static msmtp with Alpine Linux
      run: |
        docker run --rm -v "$PWD:/workspace" alpine:latest sh -c '
          # Install build dependencies
          apk add --no-cache \
            gcc \
            musl-dev \
            make \
            wget \
            tar \
            xz \
            gettext-dev \
            gnutls-dev \
            gnutls-static \
            libgsasl-dev \
            libgsasl-static \
            libidn2-dev \
            libidn2-static \
            zlib-static
          
          # Download and extract msmtp
          cd /tmp
          wget -q https://marlam.de/msmtp/releases/msmtp-1.8.25.tar.xz
          tar xf msmtp-1.8.25.tar.xz
          cd msmtp-1.8.25
          
          # Configure and build static
          CFLAGS="-static -Os" \
          LDFLAGS="-static -s" \
          ./configure \
            --prefix=/usr \
            --sysconfdir=/etc \
            --with-tls=gnutls \
            --disable-shared \
            --enable-static
          
          make -j$(nproc)
          strip --strip-all src/msmtp
          
          # Verify binary
          echo "=== Binary Info ==="
          ls -lh src/msmtp
          file src/msmtp
          ldd src/msmtp 2>&1 || echo "✅ Static binary confirmed!"
          ./src/msmtp --version
          
          # Copy to workspace
          cp src/msmtp /workspace/msmtp-linux-static
        '
    
    - name: Generate SHA256
      run: |
        sha256sum msmtp-linux-static > msmtp-linux-static.sha256
        cat msmtp-linux-static.sha256
    
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: msmtp-linux-static
        path: |
          msmtp-linux-static
          msmtp-linux-static.sha256
        retention-days: 90
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          msmtp-linux-static
          msmtp-linux-static.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**5️⃣ Click "Commit changes"** (verde, sus-dreapta)

**6️⃣ Click "Commit changes"** din popup

---

## ✅ Build-ul va Porni Automat!

După commit, mergi la:
```
https://github.com/me-suzy/msmtp-builder/actions
