name: Build Static msmtp Binary

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Download and extract static msmtp from Alpine
      run: |
        # Download Alpine APK package
        wget https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/msmtp-1.8.26-r2.apk
        
        # Extract APK (it's just a tar.gz)
        tar -xf msmtp-1.8.26-r2.apk
        
        # Copy binary
        cp usr/bin/msmtp msmtp-linux-static
        chmod +x msmtp-linux-static
        
        # Verify
        echo "=== Binary Info ==="
        ls -lh msmtp-linux-static
        file msmtp-linux-static
        ldd msmtp-linux-static 2>&1 || echo "✅ Static binary!"
        ./msmtp-linux-static --version
    
    - name: Generate SHA256
      run: |
        sha256sum msmtp-linux-static > msmtp-linux-static.sha256
        cat msmtp-linux-static.sha256
    
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: msmtp-linux-static
        path: |
          msmtp-linux-static
          msmtp-linux-static.sha256
        retention-days: 90
