name: Build Static msmtp Binary

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Build static msmtp with Alpine Linux
      run: |
        docker run --rm -v "$PWD:/workspace" alpine:latest sh -c "
          apk add --no-cache \
            gcc \
            musl-dev \
            make \
            wget \
            tar \
            xz \
            gettext-dev \
            gnutls-dev \
            gnutls-static \
            libgsasl-dev \
            libgsasl-static \
            libidn2-dev \
            libidn2-static \
            zlib-static
          
          cd /tmp
          wget -q https://marlam.de/msmtp/releases/msmtp-1.8.25.tar.xz
          tar xf msmtp-1.8.25.tar.xz
          cd msmtp-1.8.25
          
          CFLAGS='-static -Os' \
          LDFLAGS='-static -s' \
          ./configure \
            --prefix=/usr \
            --sysconfdir=/etc \
            --with-tls=gnutls \
            --disable-shared \
            --enable-static
          
          make -j\$(nproc)
          strip --strip-all src/msmtp
          
          echo '=== Binary Info ==='
          ls -lh src/msmtp
          file src/msmtp
          ldd src/msmtp 2>&1 || echo 'Static binary confirmed!'
          ./src/msmtp --version
          
          cp src/msmtp /workspace/msmtp-linux-static
        "
    
    - name: Generate SHA256
      run: |
        sha256sum msmtp-linux-static > msmtp-linux-static.sha256
        cat msmtp-linux-static.sha256
    
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: msmtp-linux-static
        path: |
          msmtp-linux-static
          msmtp-linux-static.sha256
        retention-days: 90
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          msmtp-linux-static
          msmtp-linux-static.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
