name: Build Static msmtp Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget libgnutls28-dev libgsasl7-dev libidn2-dev gettext autoconf automake libtool pkg-config
    
    - name: Download msmtp source
      run: |
        cd /tmp
        wget https://marlam.de/msmtp/releases/msmtp-1.8.25.tar.xz
        tar xf msmtp-1.8.25.tar.xz
        cd msmtp-1.8.25
    
    - name: Build static binary
      run: |
        cd /tmp/msmtp-1.8.25
        ./configure --prefix=/usr --sysconfdir=/etc --with-tls=gnutls --disable-shared --enable-static CFLAGS="-static -Os" LDFLAGS="-static -s"
        make -j$(nproc)
        strip --strip-all src/msmtp
    
    - name: Test binary
      run: |
        cd /tmp/msmtp-1.8.25/src
        ./msmtp --version
        file msmtp
        ldd msmtp || echo "Static binary - no dynamic dependencies"
    
    - name: Prepare artifact
      run: |
        mkdir -p artifact
        cp /tmp/msmtp-1.8.25/src/msmtp artifact/msmtp-linux-static
        cd artifact
        sha256sum msmtp-linux-static > msmtp-linux-static.sha256
        ls -lh
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: msmtp-linux-static
        path: |
          artifact/msmtp-linux-static
          artifact/msmtp-linux-static.sha256
        retention-days: 90